### ISSUE TITLE
Python 3.14 compatibility issues

### ISSUE THREAD

**Issue by sharkcz** [danthedeckie/simpleeval#158]
As found by the Fedora Python maintainers during their preparation for Python 3.14, the changes from PR #146 are not sufficient to resolve the depreciated `ast` module usage. Please see https://bugzilla.redhat.com/show_bug.cgi?id=2322707 for the full details. The report says
````
python-simpleeval fails to build with Python 3.14.0a1.

The AttributeError is repeated 100x.:

======================================================================
ERROR: test_trailing (__main__.TestWhitespace.test_trailing)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/python-simpleeval-1.0.1-build/simpleeval-1.0.1/test_simpleeval.py", line 40, in setUp
    self.s = SimpleEval()
             ~~~~~~~~~~^^
  File "/builddir/build/BUILD/python-simpleeval-1.0.1-build/simpleeval-1.0.1/simpleeval.py", line 389, in __init__
    if Num := getattr(ast, "Num"):
              ~~~~~~~^^^^^^^^^^^^
AttributeError: module 'ast' has no attribute 'Num'

======================================================================
FAIL: test_simpleeval_cleanup (__main__.TestReferenceCleanup.test_simpleeval_cleanup)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/python-simpleeval-1.0.1-build/simpleeval-1.0.1/test_simpleeval.py", line 1318, in tearDown
    self.assertEqual(self._initial_garbage_len, self._final_garbage_len)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 331 != 348

According to: https://docs.python.org/dev/whatsnew/3.14.html#id2
...
````

**Comment by danthedeckie** [comment]
Thanks for flagging this @sharkcz - I'll try and work on it this week.

**Comment by danthedeckie** [comment]
@sharkcz -

https://pypi.org/project/simpleeval/1.0.3/

Should fix those warnings now?

**Comment by sharkcz** [comment]
Thanks, will give it a try and report back.

**Comment by sharkcz** [comment]
I have updated the Fedora package to 1.0.3 and it looks good now, please see https://copr.fedorainfracloud.org/coprs/g/python/python3.14/build/8205961/ for details.
